### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by HadiModarres** [HadiModarres/s3_uploader_service#1]
Please keep a log of succesful uploads and also a log of errors. 

Create a folder with two files: sucessful_uploads and error
successful_uploads keeps a log of successful uploads and from which path a file was taken and at which place in what bucket and region was placed .
error will keep a record of any erros that have occured.

**Comment by HadiModarres** [comment]
put normal operation log in debug.log

**Comment by ghost** [comment]
```bash
./bin/cli.php upload\
    --log="!debug:debug.log"\
    --log="!info:success.log"\
    --log="error:error.log"
```

**Comment by HadiModarres** [comment]
this syntax doesn work me it gives an error:

bash: !info: event not found

**Comment by ghost** [comment]
Make sure to wrap it in quotes and make note of the backslash at the end of each line.\
Alternatively, try to copy-paste this:

```bash
./bin/cli.php upload  --log="!debug:debug.log" --log="!info:success.log" --log="error:error.log"
```

**Comment by HadiModarres** [comment]
yeah i did copy and paste it i still get ```bash: !info: event not found```

**Comment by ghost** [comment]
Take a look at this: https://serverfault.com/questions/208265/what-is-bash-event-not-found

Did not know that... Maybe we should use a different symbol instead of `!`.

**Comment by HadiModarres** [comment]
Mm yea lets use another one

**Comment by ghost** [comment]
Using `@` now, hopefully it fixes the issue.
