### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by HadiModarres** [HadiModarres/s3_uploader_service#2]
Create a config file "config" that would keep a configuration with default values except values for s3 key and s3 secret, and path

**Comment by ghost** [comment]
First, pass all possible config entries in the terminal and do a `--dump-config`. This will save the values into a config file:

```bash
./bin/cli.php upload ... \
    --config=config.json\
    --dump-config
```

Then, re-use the config file and only configure `--path`, `--s3-key`, `--s3-secret` and optionally `--log` via the terminal:

```bash
./bin/cli.php upload ... \
    --config=config.json
```

**Comment by HadiModarres** [comment]
config file doesnt seem to respect "delete": true. This exists in my config file but the script didnt remove files after

**Comment by ghost** [comment]
Should be fixed now.

**Comment by HadiModarres** [comment]
fixed
