### ISSUE TITLE
Rewrite Policy

### ISSUE THREAD

**Issue by HadiModarres** [HadiModarres/s3_uploader_service#4]
add another configration option that determines what to do if the file with same name exists on the same path on s3. 

options: 
1- don't upload if file with same name exists on the same path
2- rewrite (default)

**Comment by ghost** [comment]
Use `--skip-up-to-date` to skip files which exist and are of the same file size, rather than re-upload them to the bucket, which is the default.

**Comment by HadiModarres** [comment]
works as expected
